- topic_name: conveyor/velocity
  gz_type_name: gz.msgs.Double
  ros_type_name: std_msgs/msg/Float64
  lazy: true
  direction: BIDIRECTIONAL

- topic_name: conveyor/state
  gz_type_name: gz.msgs.Model
  ros_type_name: sensor_msgs/msg/JointState
  lazy: true
  direction: BIDIRECTIONAL

- topic_name: pusher/position
  gz_type_name: gz.msgs.Double
  ros_type_name: std_msgs/msg/Float64
  lazy: true
  direction: BIDIRECTIONAL

- topic_name: pusher/state
  gz_type_name: gz.msgs.Model
  ros_type_name: sensor_msgs/msg/JointState
  lazy: true
  direction: BIDIRECTIONAL

- topic_name: pusher/camera_raw
  gz_type_name: gz.msgs.Image
  ros_type_name: sensor_msgs/msg/Image
  lazy: true
  direction: BIDIRECTIONAL
